DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE web_source (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  source_name UNIQUE NOT NULL
);

CREATE TABLE event (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  source_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  event_date TIMESTAMP NOT NULL,
  FOREIGN KEY (source_id) REFERENCES web_source (id)
);